/**
 * @hupyy/cpptoc-wasm
 * C++ to C transpiler with ACSL annotations - WebAssembly module
 */

export * from './types.js';

// Re-export types for convenience
export type {
    Diagnostic,
    ACSLOptions,
    TranspileOptions,
    TranspileResult,
    WASMModule,
    TranspilerInstance,
    CreateModuleOptions,
    CreateCppToCModule
} from './types.js';

// Note: The actual WASM module exports are generated by Emscripten
// and will be available at runtime from dist/minimal/cpptoc.js and dist/full/cpptoc.js
