if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ACSLFunctionAnnotatorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ACSLFunctionAnnotatorTest[1]_tests.cmake")
else()
  add_test(ACSLFunctionAnnotatorTest_NOT_BUILT ACSLFunctionAnnotatorTest_NOT_BUILT)
endif()
