if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ACSLGeneratorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ACSLGeneratorTest[1]_tests.cmake")
else()
  add_test(ACSLGeneratorTest_NOT_BUILT ACSLGeneratorTest_NOT_BUILT)
endif()
