if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ActionTableGeneratorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ActionTableGeneratorTest[1]_tests.cmake")
else()
  add_test(ActionTableGeneratorTest_NOT_BUILT ActionTableGeneratorTest_NOT_BUILT)
endif()
