if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/AdvancedTemplateIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/AdvancedTemplateIntegrationTest[1]_tests.cmake")
else()
  add_test(AdvancedTemplateIntegrationTest_NOT_BUILT AdvancedTemplateIntegrationTest_NOT_BUILT)
endif()
