if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ArraySubscriptExprHandlerDispatcherTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ArraySubscriptExprHandlerDispatcherTest[1]_tests.cmake")
else()
  add_test(ArraySubscriptExprHandlerDispatcherTest_NOT_BUILT ArraySubscriptExprHandlerDispatcherTest_NOT_BUILT)
endif()
