if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/AutoDecayCopyTranslatorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/AutoDecayCopyTranslatorTest[1]_tests.cmake")
else()
  add_test(AutoDecayCopyTranslatorTest_NOT_BUILT AutoDecayCopyTranslatorTest_NOT_BUILT)
endif()
