if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/BaseOffsetCalculatorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/BaseOffsetCalculatorTest[1]_tests.cmake")
else()
  add_test(BaseOffsetCalculatorTest_NOT_BUILT BaseOffsetCalculatorTest_NOT_BUILT)
endif()
