if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ClassesE2ETest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ClassesE2ETest[1]_tests.cmake")
else()
  add_test(ClassesE2ETest_NOT_BUILT ClassesE2ETest_NOT_BUILT)
endif()
