if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ConstructorHandlerTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ConstructorHandlerTest[1]_tests.cmake")
else()
  add_test(ConstructorHandlerTest_NOT_BUILT ConstructorHandlerTest_NOT_BUILT)
endif()
