if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ConstructorHandlerTest_BaseChaining[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ConstructorHandlerTest_BaseChaining[1]_tests.cmake")
else()
  add_test(ConstructorHandlerTest_BaseChaining_NOT_BUILT ConstructorHandlerTest_BaseChaining_NOT_BUILT)
endif()
