if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ConstructorSplitterTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ConstructorSplitterTest[1]_tests.cmake")
else()
  add_test(ConstructorSplitterTest_NOT_BUILT ConstructorSplitterTest_NOT_BUILT)
endif()
