if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/CoroutineIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/CoroutineIntegrationTest[1]_tests.cmake")
else()
  add_test(CoroutineIntegrationTest_NOT_BUILT CoroutineIntegrationTest_NOT_BUILT)
endif()
