if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/CrossCastTraversalTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/CrossCastTraversalTest[1]_tests.cmake")
else()
  add_test(CrossCastTraversalTest_NOT_BUILT CrossCastTraversalTest_NOT_BUILT)
endif()
