if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/DeclContextTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/DeclContextTest[1]_tests.cmake")
else()
  add_test(DeclContextTest_NOT_BUILT DeclContextTest_NOT_BUILT)
endif()
