if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/DeclRefExprHandlerDispatcherTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/DeclRefExprHandlerDispatcherTest[1]_tests.cmake")
else()
  add_test(DeclRefExprHandlerDispatcherTest_NOT_BUILT DeclRefExprHandlerDispatcherTest_NOT_BUILT)
endif()
