if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/DeducingThisTranslatorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/DeducingThisTranslatorTest[1]_tests.cmake")
else()
  add_test(DeducingThisTranslatorTest_NOT_BUILT DeducingThisTranslatorTest_NOT_BUILT)
endif()
