if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/DestructorHandlerTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/DestructorHandlerTest[1]_tests.cmake")
else()
  add_test(DestructorHandlerTest_NOT_BUILT DestructorHandlerTest_NOT_BUILT)
endif()
