if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/EnumTypedefTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/EnumTypedefTest[1]_tests.cmake")
else()
  add_test(EnumTypedefTest_NOT_BUILT EnumTypedefTest_NOT_BUILT)
endif()
