if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExceptionFrameTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExceptionFrameTest[1]_tests.cmake")
else()
  add_test(ExceptionFrameTest_NOT_BUILT ExceptionFrameTest_NOT_BUILT)
endif()
