if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExceptionIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExceptionIntegrationTest[1]_tests.cmake")
else()
  add_test(ExceptionIntegrationTest_NOT_BUILT ExceptionIntegrationTest_NOT_BUILT)
endif()
