if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest_VirtualCallDetection[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest_VirtualCallDetection[1]_tests.cmake")
else()
  add_test(ExpressionHandlerTest_VirtualCallDetection_NOT_BUILT ExpressionHandlerTest_VirtualCallDetection_NOT_BUILT)
endif()
