if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerPointerAdjustmentTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerPointerAdjustmentTest[1]_tests.cmake")
else()
  add_test(ExpressionHandlerPointerAdjustmentTest_NOT_BUILT ExpressionHandlerPointerAdjustmentTest_NOT_BUILT)
endif()
