if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest_VirtualCallMultipleInheritance[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest_VirtualCallMultipleInheritance[1]_tests.cmake")
else()
  add_test(ExpressionHandlerTest_VirtualCallMultipleInheritance_NOT_BUILT ExpressionHandlerTest_VirtualCallMultipleInheritance_NOT_BUILT)
endif()
