if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest_VirtualCall[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest_VirtualCall[1]_tests.cmake")
else()
  add_test(ExpressionHandlerTest_VirtualCall_NOT_BUILT ExpressionHandlerTest_VirtualCall_NOT_BUILT)
endif()
