if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest_This[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest_This[1]_tests.cmake")
else()
  add_test(ExpressionHandlerTest_This_NOT_BUILT ExpressionHandlerTest_This_NOT_BUILT)
endif()
