if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/ExpressionHandlerTest[1]_tests.cmake")
else()
  add_test(ExpressionHandlerTest_NOT_BUILT ExpressionHandlerTest_NOT_BUILT)
endif()
