if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/FrameAllocationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/FrameAllocationTest[1]_tests.cmake")
else()
  add_test(FrameAllocationTest_NOT_BUILT FrameAllocationTest_NOT_BUILT)
endif()
