if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/GlobalVariablesIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/GlobalVariablesIntegrationTest[1]_tests.cmake")
else()
  add_test(GlobalVariablesIntegrationTest_NOT_BUILT GlobalVariablesIntegrationTest_NOT_BUILT)
endif()
