if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/HeaderCompatibilityTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/HeaderCompatibilityTest[1]_tests.cmake")
else()
  add_test(HeaderCompatibilityTest_NOT_BUILT HeaderCompatibilityTest_NOT_BUILT)
endif()
