if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/HierarchyTraversalTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/HierarchyTraversalTest[1]_tests.cmake")
else()
  add_test(HierarchyTraversalTest_NOT_BUILT HierarchyTraversalTest_NOT_BUILT)
endif()
