if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/IncludeGuardGeneratorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/IncludeGuardGeneratorTest[1]_tests.cmake")
else()
  add_test(IncludeGuardGeneratorTest_NOT_BUILT IncludeGuardGeneratorTest_NOT_BUILT)
endif()
