if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/IntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/IntegrationTest[1]_tests.cmake")
else()
  add_test(IntegrationTest_NOT_BUILT IntegrationTest_NOT_BUILT)
endif()
