if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/MemberInitListTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/MemberInitListTest[1]_tests.cmake")
else()
  add_test(MemberInitListTest_NOT_BUILT MemberInitListTest_NOT_BUILT)
endif()
