if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/MultidimSubscriptTranslatorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/MultidimSubscriptTranslatorTest[1]_tests.cmake")
else()
  add_test(MultidimSubscriptTranslatorTest_NOT_BUILT MultidimSubscriptTranslatorTest_NOT_BUILT)
endif()
