if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/NameManglerStaticMemberTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/NameManglerStaticMemberTest[1]_tests.cmake")
else()
  add_test(NameManglerStaticMemberTest_NOT_BUILT NameManglerStaticMemberTest_NOT_BUILT)
endif()
