if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/OverloadResolutionTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/OverloadResolutionTest[1]_tests.cmake")
else()
  add_test(OverloadResolutionTest_NOT_BUILT OverloadResolutionTest_NOT_BUILT)
endif()
