if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/PointersIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/PointersIntegrationTest[1]_tests.cmake")
else()
  add_test(PointersIntegrationTest_NOT_BUILT PointersIntegrationTest_NOT_BUILT)
endif()
