if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/PureVirtualHandlerTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/PureVirtualHandlerTest[1]_tests.cmake")
else()
  add_test(PureVirtualHandlerTest_NOT_BUILT PureVirtualHandlerTest_NOT_BUILT)
endif()
