if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_Vtable[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_Vtable[1]_tests.cmake")
else()
  add_test(RecordHandlerTest_Vtable_NOT_BUILT RecordHandlerTest_Vtable_NOT_BUILT)
endif()
