if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_lpVtbl[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_lpVtbl[1]_tests.cmake")
else()
  add_test(RecordHandlerTest_lpVtbl_NOT_BUILT RecordHandlerTest_lpVtbl_NOT_BUILT)
endif()
