if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_MultipleLpVtbl[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_MultipleLpVtbl[1]_tests.cmake")
else()
  add_test(RecordHandlerTest_MultipleLpVtbl_NOT_BUILT RecordHandlerTest_MultipleLpVtbl_NOT_BUILT)
endif()
