if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_VtableInstanceThunks[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_VtableInstanceThunks[1]_tests.cmake")
else()
  add_test(RecordHandlerTest_VtableInstanceThunks_NOT_BUILT RecordHandlerTest_VtableInstanceThunks_NOT_BUILT)
endif()
