if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_VtableInstance[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RecordHandlerTest_VtableInstance[1]_tests.cmake")
else()
  add_test(RecordHandlerTest_VtableInstance_NOT_BUILT RecordHandlerTest_VtableInstance_NOT_BUILT)
endif()
