if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RTTIIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RTTIIntegrationTest[1]_tests.cmake")
else()
  add_test(RTTIIntegrationTest_NOT_BUILT RTTIIntegrationTest_NOT_BUILT)
endif()
