if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RuntimeIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RuntimeIntegrationTest[1]_tests.cmake")
else()
  add_test(RuntimeIntegrationTest_NOT_BUILT RuntimeIntegrationTest_NOT_BUILT)
endif()
