if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RuntimeModeLibraryTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/RuntimeModeLibraryTest[1]_tests.cmake")
else()
  add_test(RuntimeModeLibraryTest_NOT_BUILT RuntimeModeLibraryTest_NOT_BUILT)
endif()
