if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/StatementHandlerTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/StatementHandlerTest[1]_tests.cmake")
else()
  add_test(StatementHandlerTest_NOT_BUILT StatementHandlerTest_NOT_BUILT)
endif()
