if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/StaticMethodHandlerDispatcherTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/StaticMethodHandlerDispatcherTest[1]_tests.cmake")
else()
  add_test(StaticMethodHandlerDispatcherTest_NOT_BUILT StaticMethodHandlerDispatcherTest_NOT_BUILT)
endif()
