if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/StructsIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/StructsIntegrationTest[1]_tests.cmake")
else()
  add_test(StructsIntegrationTest_NOT_BUILT StructsIntegrationTest_NOT_BUILT)
endif()
