if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/StructReturnTypeTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/StructReturnTypeTest[1]_tests.cmake")
else()
  add_test(StructReturnTypeTest_NOT_BUILT StructReturnTypeTest_NOT_BUILT)
endif()
