if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/SuspendPointIdentifierTest_GTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/SuspendPointIdentifierTest_GTest[1]_tests.cmake")
else()
  add_test(SuspendPointIdentifierTest_GTest_NOT_BUILT SuspendPointIdentifierTest_GTest_NOT_BUILT)
endif()
