if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TemplateExtractorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TemplateExtractorTest[1]_tests.cmake")
else()
  add_test(TemplateExtractorTest_NOT_BUILT TemplateExtractorTest_NOT_BUILT)
endif()
