if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TranspilerAPI_VirtualFiles_Test[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TranspilerAPI_VirtualFiles_Test[1]_tests.cmake")
else()
  add_test(TranspilerAPI_VirtualFiles_Test_NOT_BUILT TranspilerAPI_VirtualFiles_Test_NOT_BUILT)
endif()
