if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TryCatchTransformerTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TryCatchTransformerTest[1]_tests.cmake")
else()
  add_test(TryCatchTransformerTest_NOT_BUILT TryCatchTransformerTest_NOT_BUILT)
endif()
