if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TypeAliasAnalyzerTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TypeAliasAnalyzerTest[1]_tests.cmake")
else()
  add_test(TypeAliasAnalyzerTest_NOT_BUILT TypeAliasAnalyzerTest_NOT_BUILT)
endif()
