if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TypeidTranslatorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TypeidTranslatorTest[1]_tests.cmake")
else()
  add_test(TypeidTranslatorTest_NOT_BUILT TypeidTranslatorTest_NOT_BUILT)
endif()
