if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TypeInfoGeneratorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/TypeInfoGeneratorTest[1]_tests.cmake")
else()
  add_test(TypeInfoGeneratorTest_NOT_BUILT TypeInfoGeneratorTest_NOT_BUILT)
endif()
