if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/UnaryOperatorHandlerDispatcherTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/UnaryOperatorHandlerDispatcherTest[1]_tests.cmake")
else()
  add_test(UnaryOperatorHandlerDispatcherTest_NOT_BUILT UnaryOperatorHandlerDispatcherTest_NOT_BUILT)
endif()
