if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VariableHandlerTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VariableHandlerTest[1]_tests.cmake")
else()
  add_test(VariableHandlerTest_NOT_BUILT VariableHandlerTest_NOT_BUILT)
endif()
