if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VirtualBaseDetectionTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VirtualBaseDetectionTest[1]_tests.cmake")
else()
  add_test(VirtualBaseDetectionTest_NOT_BUILT VirtualBaseDetectionTest_NOT_BUILT)
endif()
