if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VirtualMethodIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VirtualMethodIntegrationTest[1]_tests.cmake")
else()
  add_test(VirtualMethodIntegrationTest_NOT_BUILT VirtualMethodIntegrationTest_NOT_BUILT)
endif()
