if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VptrInjectorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VptrInjectorTest[1]_tests.cmake")
else()
  add_test(VptrInjectorTest_NOT_BUILT VptrInjectorTest_NOT_BUILT)
endif()
