if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VtableTypedefGeneratorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VtableTypedefGeneratorTest[1]_tests.cmake")
else()
  add_test(VtableTypedefGeneratorTest_NOT_BUILT VtableTypedefGeneratorTest_NOT_BUILT)
endif()
