if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VtableGeneratorTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/VtableGeneratorTest[1]_tests.cmake")
else()
  add_test(VtableGeneratorTest_NOT_BUILT VtableGeneratorTest_NOT_BUILT)
endif()
