if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/tests/integration/ClassesIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/tests/integration/ClassesIntegrationTest[1]_tests.cmake")
else()
  add_test(ClassesIntegrationTest_NOT_BUILT ClassesIntegrationTest_NOT_BUILT)
endif()
