if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/tests/integration/EnumIntegrationTest[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/tests/integration/EnumIntegrationTest[1]_tests.cmake")
else()
  add_test(EnumIntegrationTest_NOT_BUILT EnumIntegrationTest_NOT_BUILT)
endif()
