if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/tests/integration/test_edge_cases[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/tests/integration/test_edge_cases[1]_tests.cmake")
else()
  add_test(test_edge_cases_NOT_BUILT test_edge_cases_NOT_BUILT)
endif()
