if(EXISTS "/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/tests/integration/test_error_handling[1]_tests.cmake")
  include("/Users/alexanderfedin/Projects/hapyy/hupyy-cpp-to-c/tests/integration/test_error_handling[1]_tests.cmake")
else()
  add_test(test_error_handling_NOT_BUILT test_error_handling_NOT_BUILT)
endif()
