async function createCppToC(moduleArg={}){var moduleRtn;var l=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:b}=await import("module");var require=b(import.meta.url)}var p=(b,a)=>{throw a;},da=import.meta.url,u="",ea,v;
if(ca){var fs=require("fs");da.startsWith("file:")&&(u=require("path").dirname(require("url").fileURLToPath(da))+"/");v=b=>{b=y(b)?new URL(b):b;return fs.readFileSync(b)};ea=async b=>{b=y(b)?new URL(b):b;return fs.readFileSync(b,void 0)};process.argv.slice(2);p=(b,a)=>{process.exitCode=b;throw a;}}else if(aa||ba){try{u=(new URL(".",da)).href}catch{}ba&&(v=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});ea=async b=>{if(y(b))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var a=await fetch(b,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}console.log.bind(console);var z=console.error.bind(console),B,fa=!1,ha,y=b=>b.startsWith("file://"),ia,ja,C,D,ka,la,ma,E,na,oa,pa,qa,ra=!1;
function sa(){var b=ta.buffer;C=new Int8Array(b);ka=new Int16Array(b);D=new Uint8Array(b);la=new Uint16Array(b);ma=new Int32Array(b);E=new Uint32Array(b);na=new Float32Array(b);oa=new Float64Array(b);pa=new BigInt64Array(b);qa=new BigUint64Array(b)}function ua(b){l.onAbort?.(b);b="Aborted("+b+")";z(b);fa=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ja?.(b);throw b;}var va;
async function wa(b){if(!B)try{var a=await ea(b);return new Uint8Array(a)}catch{}if(b==va&&B)b=new Uint8Array(B);else if(v)b=v(b);else throw"both async and sync fetching of the wasm failed";return b}async function xa(b,a){try{var c=await wa(b);return await WebAssembly.instantiate(c,a)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}
async function ya(b){var a=va;if(!B&&!y(a)&&!ca)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return xa(a,b)}class za{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}var Aa=b=>{for(;0<b.length;)b.shift()(l)},Ba=[],Ca=[],Da=()=>{var b=l.preRun.shift();Ca.push(b)},Ea=!0,Fa=[],Ga=0,F=0;
class Ia{constructor(b){this.Ha=b;this.ea=b-24}}var Ka=b=>{var a=F;if(!a)return H(0),0;var c=new Ia(a);E[c.ea+16>>2]=a;var d=E[c.ea+4>>2];if(!d)return H(0),a;for(var e of b){if(0===e||e===d)break;if(Ja(e,d,c.ea+16))return H(e),a}H(d);return a},La={},Ma=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function I(b){return this.ha(E[b>>2])}
var J={},K={},Na={},Oa=class extends Error{constructor(b){super(b);this.name="InternalError"}},M=(b,a,c)=>{function d(h){h=c(h);if(h.length!==b.length)throw new Oa("Mismatched type converter count");for(var m=0;m<b.length;++m)L(b[m],h[m])}b.forEach(h=>Na[h]=a);var e=Array(a.length),g=[],f=0;for(let [h,m]of a.entries())K.hasOwnProperty(m)?e[h]=K[m]:(g.push(m),J.hasOwnProperty(m)||(J[m]=[]),J[m].push(()=>{e[h]=K[m];++f;f===g.length&&d(e)}));0===g.length&&d(e)},N=b=>{for(var a="";;){var c=D[b++];if(!c)return a;
a+=String.fromCharCode(c)}},O=class extends Error{constructor(b){super(b);this.name="BindingError"}},Pa=b=>{throw new O(b);};function Qa(b,a,c={}){var d=a.name;if(!b)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(K.hasOwnProperty(b)){if(c.Oa)return;throw new O(`Cannot register type '${d}' twice`);}K[b]=a;delete Na[b];J.hasOwnProperty(b)&&(a=J[b],delete J[b],a.forEach(e=>e()))}function L(b,a,c={}){return Qa(b,a,c)}
var Ra=(b,a,c)=>{switch(a){case 1:return c?d=>C[d]:d=>D[d];case 2:return c?d=>ka[d>>1]:d=>la[d>>1];case 4:return c?d=>ma[d>>2]:d=>E[d>>2];case 8:return c?d=>pa[d>>3]:d=>qa[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Sa=b=>{throw new O(b.da.ga.fa.name+" instance already deleted");},Ta=!1,Ua=()=>{},P=b=>{if(!globalThis.FinalizationRegistry)return P=a=>a,b;Ta=new FinalizationRegistry(a=>{a=a.da;--a.count.value;0===a.count.value&&(a.ia?a.ma.na(a.ia):a.ga.fa.na(a.ea))});
P=a=>{var c=a.da;c.ia&&Ta.register(a,{da:c},a);return a};Ua=a=>{Ta.unregister(a)};return P(b)},Va=[];function Wa(){}
var Xa=(b,a)=>Object.defineProperty(a,"name",{value:b}),Ya={},Za=(b,a,c)=>{if(void 0===b[a].pa){var d=b[a];b[a]=function(...e){if(!b[a].pa.hasOwnProperty(e.length))throw new O(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].pa})!`);return b[a].pa[e.length].apply(this,e)};b[a].pa=[];b[a].pa[d.sa]=d}},$a=(b,a)=>{if(l.hasOwnProperty(b))throw new O(`Cannot register public name '${b}' twice`);l[b]=a;l[b].sa=void 0},ab=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,
"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function bb(b,a,c,d,e,g,f,h){this.name=b;this.constructor=a;this.ra=c;this.na=d;this.ka=e;this.Ja=g;this.va=f;this.Ga=h;this.Qa=[]}var cb=(b,a,c)=>{for(;a!==c;){if(!a.va)throw new O(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.va(b);a=a.ka}return b},db=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function eb(b,a){if(null===a){if(this.ya)throw new O(`null is not a valid ${this.name}`);return 0}if(!a.da)throw new O(`Cannot pass "${db(a)}" as a ${this.name}`);if(!a.da.ea)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);return cb(a.da.ea,a.da.ga.fa,this.fa)}
function fb(b,a){if(null===a){if(this.ya)throw new O(`null is not a valid ${this.name}`);if(this.xa){var c=this.za();null!==b&&b.push(this.na,c);return c}return 0}if(!a||!a.da)throw new O(`Cannot pass "${db(a)}" as a ${this.name}`);if(!a.da.ea)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.wa&&a.da.ga.wa)throw new O(`Cannot convert argument of type ${a.da.ma?a.da.ma.name:a.da.ga.name} to parameter type ${this.name}`);c=cb(a.da.ea,a.da.ga.fa,this.fa);if(this.xa){if(void 0===
a.da.ia)throw new O("Passing raw pointer to smart pointer is illegal");switch(this.Va){case 0:if(a.da.ma===this)c=a.da.ia;else throw new O(`Cannot convert argument of type ${a.da.ma?a.da.ma.name:a.da.ga.name} to parameter type ${this.name}`);break;case 1:c=a.da.ia;break;case 2:if(a.da.ma===this)c=a.da.ia;else{var d=a.clone();c=this.Ra(c,gb(()=>d["delete"]()));null!==b&&b.push(this.na,c)}break;default:throw new O("Unsupporting sharing policy");}}return c}
function hb(b,a){if(null===a){if(this.ya)throw new O(`null is not a valid ${this.name}`);return 0}if(!a.da)throw new O(`Cannot pass "${db(a)}" as a ${this.name}`);if(!a.da.ea)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.da.ga.wa)throw new O(`Cannot convert argument of type ${a.da.ga.name} to parameter type ${this.name}`);return cb(a.da.ea,a.da.ga.fa,this.fa)}
var ib=(b,a,c)=>{if(a===c)return b;if(void 0===c.ka)return null;b=ib(b,a,c.ka);return null===b?null:c.Ga(b)},jb={},kb=(b,a)=>{if(void 0===a)throw new O("ptr should not be undefined");for(;b.ka;)a=b.va(a),b=b.ka;return jb[a]},lb=(b,a)=>{if(!a.ga||!a.ea)throw new Oa("makeClassHandle requires ptr and ptrType");if(!!a.ma!==!!a.ia)throw new Oa("Both smartPtrType and smartPtr must be specified");a.count={value:1};return P(Object.create(b,{da:{value:a,writable:!0}}))};
function mb(b,a,c,d,e,g,f,h,m,n,k){this.name=b;this.fa=a;this.ya=c;this.wa=d;this.xa=e;this.Pa=g;this.Va=f;this.Ea=h;this.za=m;this.Ra=n;this.na=k;e||void 0!==a.ka?this.ja=fb:(this.ja=d?eb:hb,this.la=null)}var nb=(b,a)=>{if(!l.hasOwnProperty(b))throw new Oa("Replacing nonexistent public symbol");l[b]=a;l[b].sa=void 0},R=(b,a)=>{b=N(b);var c=Q.get(a);if("function"!=typeof c)throw new O(`unknown function pointer with signature ${b}: ${a}`);return c};class ob extends Error{}
var qb=b=>{b=pb(b);var a=N(b);S(b);return a},rb=(b,a)=>{function c(g){e[g]||K[g]||(Na[g]?Na[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};a.forEach(c);throw new ob(`${b}: `+d.map(qb).join([", "]));},tb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(E[a+4*d>>2]);return c};function ub(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].la)return!0;return!1}
function vb(b,a,c,d,e,g){var f=a.length;if(2>f)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==a[1]&&null!==c,m=ub(a);c=!a[0].Da;var n=a[0],k=a[1];d=[b,Pa,d,e,Ma,n.ha.bind(n),k?.ja.bind(k)];for(e=2;e<f;++e)n=a[e],d.push(n.ja.bind(n));if(!m)for(e=h?1:2;e<a.length;++e)null!==a[e].la&&d.push(a[e].la);m=ub(a);e=a.length-2;k=[];n=["fn"];h&&n.push("thisWired");for(f=0;f<e;++f)k.push(`arg${f}`),n.push(`arg${f}Wired`);k=k.join(",");n=n.join(",");
k=`return function (${k}) {\n`;m&&(k+="var destructors = [];\n");var r=m?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(k+=`var thisWired = toClassParamWire(${r}, this);\n`);for(f=0;f<e;++f){var t=`toArg${f}Wire`;k+=`var arg${f}Wired = ${t}(${r}, arg${f});\n`;q.push(t)}k+=(c||g?"var rv = ":"")+`invoker(${n});\n`;if(m)k+="runDestructors(destructors);\n";else for(f=h?1:2;f<a.length;++f)g=1===f?"thisWired":"arg"+(f-2)+"Wired",
null!==a[f].la&&(k+=`${g}_dtor(${g});\n`,q.push(`${g}_dtor`));c&&(k+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(q,k+"}\n"))(...d);return Xa(b,a)}
var wb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},xb=[],T=[0,1,,1,null,1,!0,1,!1,1],yb=b=>{9<b&&0===--T[b+1]&&(T[b]=void 0,xb.push(b))},zb=b=>{if(!b)throw new O(`Cannot use deleted val. handle = ${b}`);return T[b]},gb=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=xb.pop()||T.length;T[a]=b;T[a+1]=1;return a}},Ab={name:"emscripten::val",ha:b=>{var a=zb(b);yb(b);return a},ja:(b,a)=>gb(a),oa:I,la:null},Bb=(b,a)=>{switch(a){case 4:return function(c){return this.ha(na[c>>
2])};case 8:return function(c){return this.ha(oa[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},Cb=Object.assign({optional:!0},Ab),Db=(b,a,c)=>{var d=D;if(!(0<c))return 0;var e=a;c=a+c-1;for(var g=0;g<b.length;++g){var f=b.codePointAt(g);if(127>=f){if(a>=c)break;d[a++]=f}else if(2047>=f){if(a+1>=c)break;d[a++]=192|f>>6;d[a++]=128|f&63}else if(65535>=f){if(a+2>=c)break;d[a++]=224|f>>12;d[a++]=128|f>>6&63;d[a++]=128|f&63}else{if(a+3>=c)break;d[a++]=240|f>>18;d[a++]=128|f>>
12&63;d[a++]=128|f>>6&63;d[a++]=128|f&63;g++}}d[a]=0;return a-e},Eb=new TextDecoder,Fb=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},Gb=(b,a,c)=>b?Eb.decode(D.subarray(b,Fb(D,b,a,c))):"",Hb=new TextDecoder("utf-16le"),Ib=(b,a,c)=>{b>>=1;return Hb.decode(la.subarray(b,Fb(la,b,a/2,c)))},Jb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)ka[a>>1]=b.charCodeAt(e),a+=2;ka[a>>1]=0;return a-d},Kb=b=>2*b.length,Lb=(b,a,c)=>{var d="";
b>>=2;for(var e=0;!(e>=a/4);e++){var g=E[b+e];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},Mb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var g=b.codePointAt(e);65535<g&&e++;ma[a>>2]=g;a+=4;if(a+4>c)break}ma[a>>2]=0;return a-d},Nb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},Ob=0,Pb=[],Qb=b=>{var a=Pb.length;Pb.push(b);return a},Rb=(b,a)=>{for(var c=Array(b),d=0;d<b;++d){var e=d,g=E[a+4*d>>2],f=K[g];if(void 0===f)throw b=
`${`parameter ${d}`} has unknown type ${qb(g)}`,new O(b);c[e]=f}return c},Sb=(b,a,c)=>{var d=[];b=b(d,c);d.length&&(E[a>>2]=gb(d));return b},Tb={},Ub=b=>{var a=Tb[b];return void 0===a?N(b):a},W={},Vb=b=>{ha=b;Ea||0<Ob||(l.onExit?.(b),fa=!0);p(b,new za(b))},Wb=b=>{if(!fa)try{if(b(),!(Ea||0<Ob))try{ha=b=ha,Vb(b)}catch(a){a instanceof za||"unwind"==a||p(1,a)}}catch(a){a instanceof za||"unwind"==a||p(1,a)}};
(()=>{let b=Wa.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof Wa&&c instanceof Wa))return!1;var d=this.da.ga.fa,e=this.da.ea;c.da=c.da;var g=c.da.ga.fa;for(c=c.da.ea;d.ka;)e=d.va(e),d=d.ka;for(;g.ka;)c=g.va(c),g=g.ka;return d===g&&e===c},clone:function(){this.da.ea||Sa(this);if(this.da.ua)return this.da.count.value+=1,this;var c=P,d=Object,e=d.create,g=Object.getPrototypeOf(this),f=this.da;c=c(e.call(d,g,{da:{value:{count:f.count,ta:f.ta,ua:f.ua,ea:f.ea,ga:f.ga,ia:f.ia,ma:f.ma}}}));
c.da.count.value+=1;c.da.ta=!1;return c},["delete"](){this.da.ea||Sa(this);if(this.da.ta&&!this.da.ua)throw new O("Object already scheduled for deletion");Ua(this);var c=this.da;--c.count.value;0===c.count.value&&(c.ia?c.ma.na(c.ia):c.ga.fa.na(c.ea));this.da.ua||(this.da.ia=void 0,this.da.ea=void 0)},isDeleted:function(){return!this.da.ea},deleteLater:function(){this.da.ea||Sa(this);if(this.da.ta&&!this.da.ua)throw new O("Object already scheduled for deletion");Va.push(this);this.da.ta=!0;return this}});
const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(mb.prototype,{Ka(b){this.Ea&&(b=this.Ea(b));return b},Ba(b){this.na?.(b)},oa:I,ha:function(b){function a(){return this.xa?lb(this.fa.ra,{ga:this.Pa,ea:c,ma:this,ia:b}):lb(this.fa.ra,{ga:this,ea:b})}var c=this.Ka(b);if(!c)return this.Ba(b),null;var d=kb(this.fa,c);if(void 0!==d){if(0===d.da.count.value)return d.da.ea=c,d.da.ia=b,d.clone();d=d.clone();this.Ba(b);return d}d=this.fa.Ja(c);d=Ya[d];if(!d)return a.call(this);d=this.wa?d.Fa:d.pointerType;var e=ib(c,this.fa,d.fa);return null===
e?a.call(this):this.xa?lb(d.fa.ra,{ga:d,ea:e,ma:this,ia:b}):lb(d.fa.ra,{ga:d,ea:e})}});l.noExitRuntime&&(Ea=l.noExitRuntime);l.printErr&&(z=l.printErr);l.wasmBinary&&(B=l.wasmBinary);if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.shift()();l.UTF8ToString=Gb;l.stringToUTF8=(b,a,c)=>Db(b,a,c);
var pb,Xb,Yb,S,X,H,Y,Z,Zb,$b,Ja,ac,ta,Q,lc={x:b=>{var a=new Ia(b);0==C[a.ea+12]&&(C[a.ea+12]=1,Ga--);C[a.ea+13]=0;Fa.push(a);Zb(b);return ac(b)},M:()=>{X(0,0);var b=Fa.pop();$b(b.Ha);F=0},b:()=>Ka([]),i:b=>Ka([b]),m:(b,a,c)=>{var d=new Ia(b);E[d.ea+16>>2]=0;E[d.ea+4>>2]=a;E[d.ea+8>>2]=c;F=b;Ga++;throw F;},d:b=>{F||=b;throw F;},C:()=>ua(""),z:b=>{var a=La[b];delete La[b];var c=a.za,d=a.na,e=a.Ca,g=e.map(f=>f.Na).concat(e.map(f=>f.Ta));M([b],g,f=>{var h={},m,n;for([m,n]of e.entries()){const k=f[m],
r=n.La,q=n.Ma,t=f[m+e.length],w=n.Sa,A=n.Ua;h[n.Ia]={read:G=>k.ha(r(q,G)),write:(G,U)=>{var x=[];w(A,G,t.ja(x,U));Ma(x)},optional:k.optional}}return[{name:a.name,ha:k=>{var r={},q;for(q in h)r[q]=h[q].read(k);d(k);return r},ja:(k,r)=>{for(var q in h)if(!(q in r||h[q].optional))throw new TypeError(`Missing field: "${q}"`);var t=c();for(q in h)h[q].write(t,r[q]);null!==k&&k.push(d,t);return t},oa:I,la:d}]})},v:(b,a,c,d,e)=>{a=N(a);d=0n===d;let g=f=>f;if(d){const f=8*c;g=h=>BigInt.asUintN(f,h);e=g(e)}L(b,
{name:a,ha:g,ja:(f,h)=>{"number"==typeof h&&(h=BigInt(h));return h},oa:Ra(a,c,!d),la:null})},G:(b,a,c,d)=>{a=N(a);L(b,{name:a,ha:function(e){return!!e},ja:function(e,g){return g?c:d},oa:function(e){return this.ha(D[e])},la:null})},t:(b,a,c,d,e,g,f,h,m,n,k,r,q)=>{k=N(k);g=R(e,g);h&&=R(f,h);n&&=R(m,n);q=R(r,q);var t=ab(k);$a(t,function(){rb(`Cannot construct ${k} due to unbound types`,[d])});M([b,a,c],d?[d]:[],w=>{w=w[0];if(d){var A=w.fa;var G=A.ra}else G=Wa.prototype;w=Xa(k,function(...Ha){if(Object.getPrototypeOf(this)!==
U)throw new O(`Use 'new' to construct ${k}`);if(void 0===x.qa)throw new O(`${k} has no accessible constructor`);var sb=x.qa[Ha.length];if(void 0===sb)throw new O(`Tried to invoke ctor of ${k} with invalid number of parameters (${Ha.length}) - expected (${Object.keys(x.qa).toString()}) parameters instead!`);return sb.apply(this,Ha)});var U=Object.create(G,{constructor:{value:w}});w.prototype=U;var x=new bb(k,w,U,q,A,g,h,n);if(x.ka){var V;(V=x.ka).Aa??(V.Aa=[]);x.ka.Aa.push(x)}A=new mb(k,x,!0,!1,!1);
V=new mb(k+"*",x,!1,!1,!1);G=new mb(k+" const*",x,!1,!0,!1);Ya[b]={pointerType:V,Fa:G};nb(t,w);return[A,V,G]})},s:(b,a,c,d,e,g)=>{var f=tb(a,c);e=R(d,e);M([],[b],h=>{h=h[0];var m=`constructor ${h.name}`;void 0===h.fa.qa&&(h.fa.qa=[]);if(void 0!==h.fa.qa[a-1])throw new O(`Cannot register multiple constructors with identical number of parameters (${a-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.fa.qa[a-1]=()=>{rb(`Cannot construct ${h.name} due to unbound types`,
f)};M([],f,n=>{n.splice(1,0,null);h.fa.qa[a-1]=vb(m,n,null,e,g);return[]});return[]})},j:(b,a,c,d,e,g,f,h,m)=>{var n=tb(c,d);a=N(a);a=wb(a);g=R(e,g);M([],[b],k=>{function r(){rb(`Cannot call ${q} due to unbound types`,n)}k=k[0];var q=`${k.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);h&&k.fa.Qa.push(a);var t=k.fa.ra,w=t[a];void 0===w||void 0===w.pa&&w.className!==k.name&&w.sa===c-2?(r.sa=c-2,r.className=k.name,t[a]=r):(Za(t,a,q),t[a].pa[c-2]=r);M([],n,A=>{A=vb(q,A,k,g,f,m);void 0===t[a].pa?
(A.sa=c-2,t[a]=A):t[a].pa[c-2]=A;return[]});return[]})},E:b=>L(b,Ab),u:(b,a,c)=>{a=N(a);L(b,{name:a,ha:d=>d,ja:(d,e)=>e,oa:Bb(a,c),la:null})},h:(b,a,c,d,e)=>{a=N(a);let g=h=>h;if(0===d){var f=32-8*c;g=h=>h<<f>>>f;e=g(e)}L(b,{name:a,ha:g,ja:(h,m)=>m,oa:Ra(a,c,0!==d),la:null})},c:(b,a,c)=>{function d(g){return new e(C.buffer,E[g+4>>2],E[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=N(c);L(b,{name:c,ha:d,
oa:d},{Oa:!0})},O:b=>{L(b,Cb)},F:(b,a)=>{a=N(a);L(b,{name:a,ha(c){var d=Gb(c+4,E[c>>2],!0);S(c);return d},ja(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,g="string"==typeof d;if(!(g||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new O("Cannot pass non-string to std::string");if(g)for(var f=e=0;f<d.length;++f){var h=d.charCodeAt(f);127>=h?e++:2047>=h?e+=2:55296<=h&&57343>=h?(e+=4,++f):e+=3}else e=d.length;f=Xb(4+e+1);h=f+4;E[f>>2]=e;g?Db(d,h,e+1):D.set(d,h);null!==c&&c.push(S,
f);return f},oa:I,la(c){S(c)}})},q:(b,a,c)=>{c=N(c);if(2===a){var d=Ib;var e=Jb;var g=Kb}else d=Lb,e=Mb,g=Nb;L(b,{name:c,ha:f=>{var h=d(f+4,E[f>>2]*a,!0);S(f);return h},ja:(f,h)=>{if("string"!=typeof h)throw new O(`Cannot pass non-string to C++ string type ${c}`);var m=g(h),n=Xb(4+m+a);E[n>>2]=m/a;e(h,n+4,m+a);null!==f&&f.push(S,n);return n},oa:I,la(f){S(f)}})},p:(b,a,c,d,e,g)=>{La[b]={name:N(a),za:R(c,d),na:R(e,g),Ca:[]}},L:(b,a,c,d,e,g,f,h,m,n)=>{La[b].Ca.push({Ia:N(a),Na:c,La:R(d,e),Ma:g,Ta:f,
Sa:R(h,m),Ua:n})},H:(b,a)=>{a=N(a);L(b,{Da:!0,name:a,ha:()=>{},ja:()=>{}})},A:()=>{Ea=!1;Ob=0},K:(b,a,c)=>{var [d,...e]=Rb(b,a);a=d.ja.bind(d);var g=e.map(m=>m.oa.bind(m));b--;var f={toValue:zb};b=g.map((m,n)=>{var k=`argFromPtr${n}`;f[k]=m;return`${k}(args${n?"+"+8*n:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:f.getStringOrSymbol=Ub,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${b})`;d.Da||(f.toReturnWire=a,f.emval_returnValue=
Sb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(f),h))(...Object.values(f));h=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return Qb(Xa(h,c))},J:(b,a,c,d,e)=>Pb[b](a,c,d,e),I:b=>{var a=zb(b);Ma(a);yb(b)},B:(b,a)=>{W[b]&&(clearTimeout(W[b].id),delete W[b]);if(!a)return 0;var c=setTimeout(()=>{delete W[b];Wb(()=>Yb(b,performance.now()))},a);W[b]={id:c,Wa:a};return 0},
D:b=>{var a=D.length;b>>>=0;if(268435456<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(268435456,65536*Math.ceil(Math.max(b,d)/65536))-ta.buffer.byteLength+65535)/65536|0;try{ta.grow(d);sa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},a:bc,k:cc,r:dc,l:ec,n:fc,g:gc,o:hc,f:ic,w:jc,e:kc,N:b=>b,y:Vb};function bc(b,a){var c=Z();try{return Q.get(b)(a)}catch(d){Y(c);if(d!==d+0)throw d;X(1,0)}}
function kc(b,a,c,d,e,g,f,h,m,n,k){var r=Z();try{Q.get(b)(a,c,d,e,g,f,h,m,n,k)}catch(q){Y(r);if(q!==q+0)throw q;X(1,0)}}function gc(b,a){var c=Z();try{Q.get(b)(a)}catch(d){Y(c);if(d!==d+0)throw d;X(1,0)}}function hc(b,a,c){var d=Z();try{Q.get(b)(a,c)}catch(e){Y(d);if(e!==e+0)throw e;X(1,0)}}function dc(b,a,c,d){var e=Z();try{return Q.get(b)(a,c,d)}catch(g){Y(e);if(g!==g+0)throw g;X(1,0)}}function cc(b,a,c){var d=Z();try{return Q.get(b)(a,c)}catch(e){Y(d);if(e!==e+0)throw e;X(1,0)}}
function fc(b){var a=Z();try{Q.get(b)()}catch(c){Y(a);if(c!==c+0)throw c;X(1,0)}}function ec(b,a,c,d,e){var g=Z();try{return Q.get(b)(a,c,d,e)}catch(f){Y(g);if(f!==f+0)throw f;X(1,0)}}function ic(b,a,c,d){var e=Z();try{Q.get(b)(a,c,d)}catch(g){Y(e);if(g!==g+0)throw g;X(1,0)}}function jc(b,a,c,d,e){var g=Z();try{Q.get(b)(a,c,d,e)}catch(f){Y(g);if(f!==f+0)throw f;X(1,0)}}var mc;
mc=await (async function(){function b(c){c=mc=c.exports;pb=c.R;Xb=c.T;Yb=c.U;S=c.V;X=c.W;H=c.X;Y=c.Y;Z=c.Z;Zb=c._;$b=c.$;Ja=c.aa;ac=c.ba;ta=c.P;Q=c.S;sa();return mc}var a={a:lc};if(l.instantiateWasm)return new Promise(c=>{l.instantiateWasm(a,(d,e)=>{c(b(d,e))})});va??=l.locateFile?l.locateFile?l.locateFile("cpptoc-minimal.wasm",u):u+"cpptoc-minimal.wasm":(new URL("cpptoc-minimal.wasm",import.meta.url)).href;return b((await ya(a)).instance)}());
(function(){function b(){l.calledRun=!0;if(!fa){ra=!0;mc.Q();ia?.(l);l.onRuntimeInitialized?.();if(l.postRun)for("function"==typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var a=l.postRun.shift();Ba.push(a)}Aa(Ba)}}if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)Da();Aa(Ca);l.setStatus?(l.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>l.setStatus(""),1);b()},1)):b()})();ra?moduleRtn=l:moduleRtn=new Promise((b,a)=>{ia=b;ja=a});
;return moduleRtn}export default createCppToC;
