#!/bin/bash
# Test Script for Phase 1: Stop Hook MVP
# Run this to execute all 3 test scenarios for Stop hook

echo "================================"
echo "Stop Hook Testing Suite"
echo "Phase 1: Autonomous Completion Verification"
echo "================================"
echo ""

# Test 1: Incomplete Work Continuation
echo "TEST 1: Incomplete Work Continuation"
echo "------------------------------------"
echo "Task: Create calculateSum function with tests"
echo ""
echo "Expected behavior:"
echo "  1. Claude implements function"
echo "  2. If Claude skips tests, Stop hook should BLOCK"
echo "  3. Hook provides specific guidance: 'Write unit tests for calculateSum...'"
echo "  4. Claude continues and writes tests"
echo "  5. Stop hook APPROVES when tests complete"
echo ""
echo "Run this command in a NEW terminal:"
echo "  claude 'Create a function called calculateSum that adds two numbers. Write unit tests for it.'"
echo ""
read -p "Press ENTER when you've run Test 1 and want to proceed to Test 2..."
echo ""

# Test 2: Complete Work Approval
echo "TEST 2: Complete Work Approval"
echo "-------------------------------"
echo "Task: Simple function (no tests requested)"
echo ""
echo "Expected behavior:"
echo "  1. Claude implements simple function"
echo "  2. Stop hook fires and verifies completion"
echo "  3. Hook APPROVES (no tests requested, work complete)"
echo "  4. Claude stops normally"
echo "  5. No continuation, clean stop"
echo ""
echo "Run this command in a NEW terminal:"
echo "  claude 'Write a function that returns Hello World'"
echo ""
read -p "Press ENTER when you've run Test 2 and want to proceed to Test 3..."
echo ""

# Test 3: Loop Prevention
echo "TEST 3: Infinite Loop Prevention"
echo "---------------------------------"
echo "Task: Intentionally ambiguous to test safety limit"
echo ""
echo "Expected behavior:"
echo "  1. Claude makes improvements"
echo "  2. Stop hook blocks 1-3 times with continuation guidance"
echo "  3. After 3 continuations, hook APPROVES (safety limit)"
echo "  4. Claude stops (no infinite loop)"
echo ""
echo "Run this command in a NEW terminal:"
echo "  claude 'Add better error handling to this project' -p /tmp/test-stop-hook-dummy-project"
echo ""
echo "Note: This test needs a dummy project. Create one first:"
echo "  mkdir -p /tmp/test-stop-hook-dummy-project"
echo "  echo 'function test() { return 1; }' > /tmp/test-stop-hook-dummy-project/index.js"
echo ""
read -p "Press ENTER when you've run Test 3..."
echo ""

# Summary
echo "================================"
echo "Testing Complete!"
echo "================================"
echo ""
echo "Review your test results:"
echo ""
echo "Success criteria:"
echo "  ✓ Test 1: Hook blocked when tests missing, continued when added"
echo "  ✓ Test 2: Hook approved immediately (work complete)"
echo "  ✓ Test 3: Hook approved after max 3 continuations"
echo ""
echo "If 2/3 tests passed: SUCCESS - Stop hook working"
echo "If 1/3 or 0/3 passed: NEEDS TUNING - adjust prompt"
echo ""
echo "Next steps:"
echo "  - Use Stop hook for 3-5 real tasks over 2-5 days"
echo "  - Monitor decision quality and latency"
echo "  - If >70% accuracy: Proceed to Phase 2"
echo ""
echo "Rollback if needed:"
echo "  cp ~/.claude/settings.json.backup-before-autonomous ~/.claude/settings.json"
echo ""
